import React from 'react';
import styled from 'styled-components';
import { FiBarChart2, FiTrendingUp, FiFileText, FiGitMerge, FiArrowRight } from 'react-icons/fi';
import type { ReportData } from '../types/index.ts';

// Mock data - This would be generated by Gemini based on test answers
export const mockReport: ReportData = {
  skillProficiency: {
    overall: 85,
    breakdown: [
      { skill: 'Communication', score: 90 },
      { skill: 'Problem Solving', score: 80 },
      { skill: 'Teamwork', score: 70 },
      { skill: 'Leadership', score: 75 },
      { skill: 'Technical', score: 88 },
    ],
  },
  careerReadiness: 92,
  summary: "You're well-prepared for a career in Software Engineering, with strong foundational skills. Continue focusing on leadership and advanced technical skills to excel.",
  recommendedSkills: ['Advanced Python', 'Cloud Computing', 'Agile Methodologies', 'Project Management'],
  learningPaths: [
    { id: 1, title: 'Software Engineering Mastery', description: 'A comprehensive path covering advanced programming, system design, and agile practices.' },
    { id: 2, title: 'Data Science Fundamentals', description: 'Learn the core concepts of data science, including data analysis and machine learning.' },
  ],
};


// Styled Components
const ReportWrapper = styled.div`
  background-color: #f8fafc;
  padding: 2rem;
  font-family: sans-serif;
`;

const Header = styled.div`
  margin-bottom: 2rem;
`;

const MainTitle = styled.h1`
  font-size: 2.25rem;
  color: #1e293b;
`;

const Subtitle = styled.p`
  color: #64748b;
  font-size: 1.1rem;
`;

const CardGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
  gap: 1.5rem;
`;

const Card = styled.div`
  background-color: white;
  padding: 1.5rem;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
`;

const CardTitle = styled.h3`
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 1.2rem;
  color: #334155;
  margin-bottom: 1rem;
`;

const CardContent = styled.div``;

// Skill Proficiency Chart Components
const BarChartContainer = styled.div`
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
`;

const BarWrapper = styled.div`
  display: flex;
  align-items: center;
  gap: 1rem;
`;

const BarLabel = styled.span`
  width: 120px;
  font-size: 0.9rem;
  color: #475569;
`;

const BarBackground = styled.div`
  flex-grow: 1;
  background-color: #f1f5f9;
  border-radius: 4px;
  height: 20px;
`;

const BarFill = styled.div<{ width: number }>`
  width: ${props => props.width}%;
  background-color: #3b82f6;
  height: 100%;
  border-radius: 4px;
  transition: width 0.5s ease-out;
`;

// Recommended Skills
const SkillsContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
`;

const SkillTag = styled.span`
  background-color: #e0e7ff;
  color: #4338ca;
  padding: 0.25rem 0.75rem;
  border-radius: 999px;
  font-size: 0.85rem;
  font-weight: 500;
`;

// Learning Paths
const LearningPathCard = styled.div`
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 1rem;
`;

const LearningPathTitle = styled.h4`
  font-size: 1.1rem;
  color: #1e293b;
  margin-bottom: 0.5rem;
`;

const LearningPathDescription = styled.p`
  color: #64748b;
  margin-bottom: 1.5rem;
`;

const ExploreButton = styled.button`
  background: none;
  border: 1px solid #cbd5e1;
  color: #334155;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  
  &:hover {
    background-color: #f8fafc;
  }
`;

interface Step3Props {
  reportData: ReportData;
}

const Step3_Report: React.FC<Step3Props> = ({ reportData }) => {
  return (
    <ReportWrapper>
      <Header>
        <MainTitle>Your Career Assessment Report</MainTitle>
        <Subtitle>Review your personalized career readiness insights and recommended next steps.</Subtitle>
      </Header>
      
      <CardGrid>
        {/* Skill Proficiency */}
        <Card>
          <CardTitle><FiBarChart2 /> Skill Proficiency</CardTitle>
          <CardContent>
            <BarChartContainer>
              {reportData.skillProficiency.breakdown.map(item => (
                <BarWrapper key={item.skill}>
                  <BarLabel>{item.skill}</BarLabel>
                  <BarBackground>
                    <BarFill width={item.score} />
                  </BarBackground>
                </BarWrapper>
              ))}
            </BarChartContainer>
          </CardContent>
        </Card>

        {/* Career Readiness */}
        <Card>
          <CardTitle><FiTrendingUp /> Career Readiness</CardTitle>
          <CardContent>
            <p style={{fontSize: '3rem', fontWeight: 'bold', color: '#16a34a'}}>{reportData.careerReadiness}%</p>
            <p style={{color: '#64748b'}}>Progress over the last 6 months.</p>
          </CardContent>
        </Card>
      </CardGrid>

      <Card style={{marginTop: '1.5rem'}}>
        <CardTitle><FiFileText /> Career Readiness Summary</CardTitle>
        <CardContent>
          <p>{reportData.summary}</p>
        </CardContent>
      </Card>
      
      <Card style={{marginTop: '1.5rem'}}>
        <CardTitle><FiGitMerge /> Recommended Next Skills</CardTitle>
        <CardContent>
          <SkillsContainer>
            {reportData.recommendedSkills.map(skill => <SkillTag key={skill}>{skill}</SkillTag>)}
          </SkillsContainer>
        </CardContent>
      </Card>

      <div style={{marginTop: '1.5rem'}}>
        <h2 style={{color: '#1e293b', marginBottom: '1rem'}}>Suggested Learning Paths</h2>
        <CardGrid>
          {reportData.learningPaths.map(path => (
            <LearningPathCard key={path.id}>
              <LearningPathTitle>{path.title}</LearningPathTitle>
              <LearningPathDescription>{path.description}</LearningPathDescription>
              <ExploreButton>Explore Path <FiArrowRight /></ExploreButton>
            </LearningPathCard>
          ))}
        </CardGrid>
      </div>

    </ReportWrapper>
  );
};

export default Step3_Report;